fix: Servlet.service() exception
SEVERE: Servlet.service() for servlet [MainMenu] in context with path
[/ListerWeb] threw exception
java.lang.IllegalStateException: Cannot forward after response has been
committed

exception due to fall through to end of doPost() function where
sendToMainIndex() would be called, which would try to call
Request.RequestDispatcher.forward() on the same request that was
forwarded just before our new Return statements